Update consistency in builders setters.
facile-it/php-openid-client pull request #10
Opened 2021-03-15 10:25 UTC by drupol

In order to have a consistency across all the builders,

I propose to:

- [x] Rename `MetadataProviderBuilder::setClient()` into `MetadataProviderBuilder::setHttpClient()`

2021-03-15 14:31 UTC, Jean85 requested changes
This is a breaking change. We should mirror the method and deprecate the old name to reduce the need for a major version bump.

2021-03-16 12:10 UTC, thomasvargiu commented
I have some doubts about changing the http client setters and getters to "client". In our domain there is another entity named "client". @drupol @Jean85 what do you think?

2021-03-16 12:12 UTC, drupol commented
I would use `setHttpClient` for sure to avoid any confusion.

2021-03-16 12:17 UTC, thomasvargiu commented
Oh sorry, you're right, I read it in the wrong way 👍

2021-03-16 12:17 UTC, merged

2021-03-16 12:20 UTC, drupol commented
Grazie a voi !