Support authorization endpoint containing query params
facile-it/php-openid-client pull request #26
Opened 2023-02-20 16:02 UTC by antonioeatgoat

Right now, if the well-known url provides an authorization endpoint containing a query, the `AuthorizationService` will build a wrong url, which will eventually contains the symbol `?` twice.

This PR adds the unit test to spot the case, so adds some checks on the uri generation in order to prevent the problem.
Even better would be to have to separate tests, one for the uri containing params and one for the uri without params, but this is up to you.

I wasn't able to perform a `composer run psalm` before opening the PR since it looks broken, I am sorry.

2023-02-20 16:20 UTC, thomasvargiu requested changes
Thank you! It's ok, just few changes.

2023-02-20 16:20 UTC, thomasvargiu commented on src/Service/AuthorizationService.php
> +        $splitUrl = explode('?', $endpointUri);
Just to be more strict, can you set the limit argument to `2`?

2023-02-20 16:20 UTC, thomasvargiu commented on tests/Service/AuthorizationServiceTest.php
> +        $issuerMetadata->getAuthorizationEndpoint()->willReturn('https://foo-endpoint?param=value');
It's a condition, can you add another test for it?

2023-02-21 09:52 UTC, merged

2023-02-21 09:52 UTC, thomasvargiu commented
Thanks @antonioeatgoat! Give me some time to fix psalm issues and I'll release it

2023-02-21 09:56 UTC, antonioeatgoat commented
Thank you @thomasvargiu for the very quick feedback!

2023-02-21 12:10 UTC, thomasvargiu commented
Released in [0.3.3](https://github.com/facile-it/php-openid-client/releases/tag/0.3.3)